version: '3'
services:
  lnd:
    build: ./lnd
    image: cherijs/lnd:latest
    container_name: bob
    restart: always
    ports:
    - "10011:10009"
    volumes:
    - ./lnd/lnd.conf:/root/.lnd/lnd.conf
    - bitcoin:/root/.bitcoin/
    - lnd_bob:/root/.lnd/ # data persistence


volumes:
  bitcoin:
    driver: local
    driver_opts:
      type: none
      device: "/Users/cherijs/.docker_volumes/.bitcoin"
      o: bind
  lnd_bob:
    driver: local
    driver_opts:
      type: none
      device: "/Users/cherijs/.docker_volumes/simnet/bob"
      o: bind